// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package billingengine

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingSchedule struct {
	ID      int32
	LoanID  int32
	Week    int32
	Amount  pgtype.Numeric
	DueDate pgtype.Date
	Paid    pgtype.Bool
}

type Borrower struct {
	ID        int32
	Createdat pgtype.Timestamp
	Updatedat pgtype.Timestamp
	Deletedat pgtype.Timestamp
	Name      string
	Email     string
	Phone     string
}

type Loan struct {
	ID                int32
	Createdat         pgtype.Timestamp
	Updatedat         pgtype.Timestamp
	Deletedat         pgtype.Timestamp
	BorrowerID        int32
	Amount            pgtype.Numeric
	InterestRate      pgtype.Numeric
	DurationWeeks     int32
	Outstanding       pgtype.Numeric
	DelinquentWeeks   int32
	InstallmentAmount pgtype.Numeric
}

type TemplateTable struct {
	ID        int32
	Createdat pgtype.Timestamp
	Updatedat pgtype.Timestamp
	Deletedat pgtype.Timestamp
}
